import { Geist, Geist_Mono } from "next/font/google";
import { Outfit, Ovo, Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../contexts/AuthContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfitFont = Outfit({
  subsets: ["latin"],
  weight: ["600"],
  variable: "--font-outfit",
});
const ovoFont = Ovo({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ovo",
});
const poppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfitFont.variable} ${ovoFont.variable} ${poppinsFont.variable} antialiased`}
      >
        <AuthProvider>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 3000,
            }}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
